apiVersion: v1
kind: PersistentVolume
metadata:
  name: lexi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ls/GolandProjects/GoVocab-CLI/decks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lexi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
