apiVersion: v1
kind: Service
metadata:
  name: lexilearn-deployment
spec:
  type: LoadBalancer
  selector:
    app: lexilearn
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
